/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SupplierPortalRouteImport } from './routes/supplier-portal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomRequestsRouteImport } from './routes/custom-requests'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierPortalIndexRouteImport } from './routes/supplier-portal.index'
import { Route as RfqIndexRouteImport } from './routes/rfq.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as CustomRequestsIndexRouteImport } from './routes/custom-requests.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as SupplierPortalVerificationRouteImport } from './routes/supplier-portal.verification'
import { Route as SupplierPortalQuoteRequestsRouteImport } from './routes/supplier-portal.quote-requests'
import { Route as SupplierPortalPreviewRouteImport } from './routes/supplier-portal.preview'
import { Route as SupplierPortalOrdersRouteImport } from './routes/supplier-portal.orders'
import { Route as SupplierPortalMessagesRouteImport } from './routes/supplier-portal.messages'
import { Route as SupplierPortalInventoryRouteImport } from './routes/supplier-portal.inventory'
import { Route as RfqNewRouteImport } from './routes/rfq.new'
import { Route as RfqIdRouteImport } from './routes/rfq.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OnboardingSupplierRouteImport } from './routes/onboarding.supplier'
import { Route as OnboardingBuyerRouteImport } from './routes/onboarding.buyer'
import { Route as OffersIdRouteImport } from './routes/offers.$id'
import { Route as DashboardSupplierRouteImport } from './routes/dashboard.supplier'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as CustomRequestsIdRouteImport } from './routes/custom-requests.$id'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminSafetyRouteImport } from './routes/admin.safety'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProductReviewRouteImport } from './routes/admin.product-review'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminBuyersRouteImport } from './routes/admin.buyers'
import { Route as SupplierPortalProductsIndexRouteImport } from './routes/supplier-portal.products.index'
import { Route as SupplierPortalProductsNewRouteImport } from './routes/supplier-portal.products.new'
import { Route as OffersIdCheckoutRouteImport } from './routes/offers.$id.checkout'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPortalRoute = SupplierPortalRouteImport.update({
  id: '/supplier-portal',
  path: '/supplier-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRequestsRoute = CustomRequestsRouteImport.update({
  id: '/custom-requests',
  path: '/custom-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPortalIndexRoute = SupplierPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const RfqIndexRoute = RfqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RfqRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OffersRoute,
} as any)
const CustomRequestsIndexRoute = CustomRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomRequestsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)
const SupplierPortalVerificationRoute =
  SupplierPortalVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalQuoteRequestsRoute =
  SupplierPortalQuoteRequestsRouteImport.update({
    id: '/quote-requests',
    path: '/quote-requests',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalPreviewRoute = SupplierPortalPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalOrdersRoute = SupplierPortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalMessagesRoute = SupplierPortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalInventoryRoute = SupplierPortalInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const RfqNewRoute = RfqNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RfqRoute,
} as any)
const RfqIdRoute = RfqIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RfqRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const OnboardingSupplierRoute = OnboardingSupplierRouteImport.update({
  id: '/onboarding/supplier',
  path: '/onboarding/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBuyerRoute = OnboardingBuyerRouteImport.update({
  id: '/onboarding/buyer',
  path: '/onboarding/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OffersRoute,
} as any)
const DashboardSupplierRoute = DashboardSupplierRouteImport.update({
  id: '/dashboard/supplier',
  path: '/dashboard/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRequestsIdRoute = CustomRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomRequestsRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductReviewRoute = AdminProductReviewRouteImport.update({
  id: '/product-review',
  path: '/product-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuyersRoute = AdminBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AdminRoute,
} as any)
const SupplierPortalProductsIndexRoute =
  SupplierPortalProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalProductsNewRoute =
  SupplierPortalProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const OffersIdCheckoutRoute = OffersIdCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => OffersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/custom-requests': typeof CustomRequestsRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/offers': typeof OffersRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/rfq': typeof RfqRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/supplier-portal': typeof SupplierPortalRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-review': typeof AdminProductReviewRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/custom-requests/$id': typeof CustomRequestsIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
  '/offers/$id': typeof OffersIdRouteWithChildren
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/supplier': typeof OnboardingSupplierRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/supplier-portal/inventory': typeof SupplierPortalInventoryRoute
  '/supplier-portal/messages': typeof SupplierPortalMessagesRoute
  '/supplier-portal/orders': typeof SupplierPortalOrdersRoute
  '/supplier-portal/preview': typeof SupplierPortalPreviewRoute
  '/supplier-portal/quote-requests': typeof SupplierPortalQuoteRequestsRoute
  '/supplier-portal/verification': typeof SupplierPortalVerificationRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/custom-requests/': typeof CustomRequestsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/supplier-portal/': typeof SupplierPortalIndexRoute
  '/offers/$id/checkout': typeof OffersIdCheckoutRoute
  '/supplier-portal/products/new': typeof SupplierPortalProductsNewRoute
  '/supplier-portal/products/': typeof SupplierPortalProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-review': typeof AdminProductReviewRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/custom-requests/$id': typeof CustomRequestsIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
  '/offers/$id': typeof OffersIdRouteWithChildren
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/supplier': typeof OnboardingSupplierRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/supplier-portal/inventory': typeof SupplierPortalInventoryRoute
  '/supplier-portal/messages': typeof SupplierPortalMessagesRoute
  '/supplier-portal/orders': typeof SupplierPortalOrdersRoute
  '/supplier-portal/preview': typeof SupplierPortalPreviewRoute
  '/supplier-portal/quote-requests': typeof SupplierPortalQuoteRequestsRoute
  '/supplier-portal/verification': typeof SupplierPortalVerificationRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/admin': typeof AdminIndexRoute
  '/custom-requests': typeof CustomRequestsIndexRoute
  '/offers': typeof OffersIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/rfq': typeof RfqIndexRoute
  '/supplier-portal': typeof SupplierPortalIndexRoute
  '/offers/$id/checkout': typeof OffersIdCheckoutRoute
  '/supplier-portal/products/new': typeof SupplierPortalProductsNewRoute
  '/supplier-portal/products': typeof SupplierPortalProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/custom-requests': typeof CustomRequestsRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/offers': typeof OffersRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/rfq': typeof RfqRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/supplier-portal': typeof SupplierPortalRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-review': typeof AdminProductReviewRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/custom-requests/$id': typeof CustomRequestsIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
  '/offers/$id': typeof OffersIdRouteWithChildren
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/supplier': typeof OnboardingSupplierRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/supplier-portal/inventory': typeof SupplierPortalInventoryRoute
  '/supplier-portal/messages': typeof SupplierPortalMessagesRoute
  '/supplier-portal/orders': typeof SupplierPortalOrdersRoute
  '/supplier-portal/preview': typeof SupplierPortalPreviewRoute
  '/supplier-portal/quote-requests': typeof SupplierPortalQuoteRequestsRoute
  '/supplier-portal/verification': typeof SupplierPortalVerificationRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/custom-requests/': typeof CustomRequestsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/supplier-portal/': typeof SupplierPortalIndexRoute
  '/offers/$id/checkout': typeof OffersIdCheckoutRoute
  '/supplier-portal/products/new': typeof SupplierPortalProductsNewRoute
  '/supplier-portal/products/': typeof SupplierPortalProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/custom-requests'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/products'
    | '/rfq'
    | '/search'
    | '/settings'
    | '/signup'
    | '/supplier-portal'
    | '/suppliers'
    | '/unauthorized'
    | '/admin/buyers'
    | '/admin/disputes'
    | '/admin/listings'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-review'
    | '/admin/requests'
    | '/admin/safety'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/verification'
    | '/custom-requests/$id'
    | '/dashboard/buyer'
    | '/dashboard/supplier'
    | '/offers/$id'
    | '/onboarding/buyer'
    | '/onboarding/supplier'
    | '/orders/$id'
    | '/products/$id'
    | '/rfq/$id'
    | '/rfq/new'
    | '/supplier-portal/inventory'
    | '/supplier-portal/messages'
    | '/supplier-portal/orders'
    | '/supplier-portal/preview'
    | '/supplier-portal/quote-requests'
    | '/supplier-portal/verification'
    | '/suppliers/$id'
    | '/admin/'
    | '/custom-requests/'
    | '/offers/'
    | '/onboarding/'
    | '/orders/'
    | '/products/'
    | '/rfq/'
    | '/supplier-portal/'
    | '/offers/$id/checkout'
    | '/supplier-portal/products/new'
    | '/supplier-portal/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/search'
    | '/settings'
    | '/signup'
    | '/suppliers'
    | '/unauthorized'
    | '/admin/buyers'
    | '/admin/disputes'
    | '/admin/listings'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-review'
    | '/admin/requests'
    | '/admin/safety'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/verification'
    | '/custom-requests/$id'
    | '/dashboard/buyer'
    | '/dashboard/supplier'
    | '/offers/$id'
    | '/onboarding/buyer'
    | '/onboarding/supplier'
    | '/orders/$id'
    | '/products/$id'
    | '/rfq/$id'
    | '/rfq/new'
    | '/supplier-portal/inventory'
    | '/supplier-portal/messages'
    | '/supplier-portal/orders'
    | '/supplier-portal/preview'
    | '/supplier-portal/quote-requests'
    | '/supplier-portal/verification'
    | '/suppliers/$id'
    | '/admin'
    | '/custom-requests'
    | '/offers'
    | '/onboarding'
    | '/orders'
    | '/products'
    | '/rfq'
    | '/supplier-portal'
    | '/offers/$id/checkout'
    | '/supplier-portal/products/new'
    | '/supplier-portal/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/custom-requests'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/products'
    | '/rfq'
    | '/search'
    | '/settings'
    | '/signup'
    | '/supplier-portal'
    | '/suppliers'
    | '/unauthorized'
    | '/admin/buyers'
    | '/admin/disputes'
    | '/admin/listings'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/product-review'
    | '/admin/requests'
    | '/admin/safety'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/verification'
    | '/custom-requests/$id'
    | '/dashboard/buyer'
    | '/dashboard/supplier'
    | '/offers/$id'
    | '/onboarding/buyer'
    | '/onboarding/supplier'
    | '/orders/$id'
    | '/products/$id'
    | '/rfq/$id'
    | '/rfq/new'
    | '/supplier-portal/inventory'
    | '/supplier-portal/messages'
    | '/supplier-portal/orders'
    | '/supplier-portal/preview'
    | '/supplier-portal/quote-requests'
    | '/supplier-portal/verification'
    | '/suppliers/$id'
    | '/admin/'
    | '/custom-requests/'
    | '/offers/'
    | '/onboarding/'
    | '/orders/'
    | '/products/'
    | '/rfq/'
    | '/supplier-portal/'
    | '/offers/$id/checkout'
    | '/supplier-portal/products/new'
    | '/supplier-portal/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomRequestsRoute: typeof CustomRequestsRouteWithChildren
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OffersRoute: typeof OffersRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  RfqRoute: typeof RfqRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SupplierPortalRoute: typeof SupplierPortalRouteWithChildren
  SuppliersRoute: typeof SuppliersRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardSupplierRoute: typeof DashboardSupplierRoute
  OnboardingBuyerRoute: typeof OnboardingBuyerRoute
  OnboardingSupplierRoute: typeof OnboardingSupplierRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-portal': {
      id: '/supplier-portal'
      path: '/supplier-portal'
      fullPath: '/supplier-portal'
      preLoaderRoute: typeof SupplierPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-requests': {
      id: '/custom-requests'
      path: '/custom-requests'
      fullPath: '/custom-requests'
      preLoaderRoute: typeof CustomRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-portal/': {
      id: '/supplier-portal/'
      path: '/'
      fullPath: '/supplier-portal/'
      preLoaderRoute: typeof SupplierPortalIndexRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/rfq/': {
      id: '/rfq/'
      path: '/'
      fullPath: '/rfq/'
      preLoaderRoute: typeof RfqIndexRouteImport
      parentRoute: typeof RfqRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof OffersRoute
    }
    '/custom-requests/': {
      id: '/custom-requests/'
      path: '/'
      fullPath: '/custom-requests/'
      preLoaderRoute: typeof CustomRequestsIndexRouteImport
      parentRoute: typeof CustomRequestsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/supplier-portal/verification': {
      id: '/supplier-portal/verification'
      path: '/verification'
      fullPath: '/supplier-portal/verification'
      preLoaderRoute: typeof SupplierPortalVerificationRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/quote-requests': {
      id: '/supplier-portal/quote-requests'
      path: '/quote-requests'
      fullPath: '/supplier-portal/quote-requests'
      preLoaderRoute: typeof SupplierPortalQuoteRequestsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/preview': {
      id: '/supplier-portal/preview'
      path: '/preview'
      fullPath: '/supplier-portal/preview'
      preLoaderRoute: typeof SupplierPortalPreviewRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/orders': {
      id: '/supplier-portal/orders'
      path: '/orders'
      fullPath: '/supplier-portal/orders'
      preLoaderRoute: typeof SupplierPortalOrdersRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/messages': {
      id: '/supplier-portal/messages'
      path: '/messages'
      fullPath: '/supplier-portal/messages'
      preLoaderRoute: typeof SupplierPortalMessagesRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/inventory': {
      id: '/supplier-portal/inventory'
      path: '/inventory'
      fullPath: '/supplier-portal/inventory'
      preLoaderRoute: typeof SupplierPortalInventoryRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/rfq/new': {
      id: '/rfq/new'
      path: '/new'
      fullPath: '/rfq/new'
      preLoaderRoute: typeof RfqNewRouteImport
      parentRoute: typeof RfqRoute
    }
    '/rfq/$id': {
      id: '/rfq/$id'
      path: '/$id'
      fullPath: '/rfq/$id'
      preLoaderRoute: typeof RfqIdRouteImport
      parentRoute: typeof RfqRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/onboarding/supplier': {
      id: '/onboarding/supplier'
      path: '/onboarding/supplier'
      fullPath: '/onboarding/supplier'
      preLoaderRoute: typeof OnboardingSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/buyer': {
      id: '/onboarding/buyer'
      path: '/onboarding/buyer'
      fullPath: '/onboarding/buyer'
      preLoaderRoute: typeof OnboardingBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$id': {
      id: '/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof OffersRoute
    }
    '/dashboard/supplier': {
      id: '/dashboard/supplier'
      path: '/dashboard/supplier'
      fullPath: '/dashboard/supplier'
      preLoaderRoute: typeof DashboardSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-requests/$id': {
      id: '/custom-requests/$id'
      path: '/$id'
      fullPath: '/custom-requests/$id'
      preLoaderRoute: typeof CustomRequestsIdRouteImport
      parentRoute: typeof CustomRequestsRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-review': {
      id: '/admin/product-review'
      path: '/product-review'
      fullPath: '/admin/product-review'
      preLoaderRoute: typeof AdminProductReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buyers': {
      id: '/admin/buyers'
      path: '/buyers'
      fullPath: '/admin/buyers'
      preLoaderRoute: typeof AdminBuyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supplier-portal/products/': {
      id: '/supplier-portal/products/'
      path: '/products'
      fullPath: '/supplier-portal/products/'
      preLoaderRoute: typeof SupplierPortalProductsIndexRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/products/new': {
      id: '/supplier-portal/products/new'
      path: '/products/new'
      fullPath: '/supplier-portal/products/new'
      preLoaderRoute: typeof SupplierPortalProductsNewRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/offers/$id/checkout': {
      id: '/offers/$id/checkout'
      path: '/checkout'
      fullPath: '/offers/$id/checkout'
      preLoaderRoute: typeof OffersIdCheckoutRouteImport
      parentRoute: typeof OffersIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuyersRoute: typeof AdminBuyersRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductReviewRoute: typeof AdminProductReviewRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSafetyRoute: typeof AdminSafetyRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuyersRoute: AdminBuyersRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductReviewRoute: AdminProductReviewRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSafetyRoute: AdminSafetyRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomRequestsRouteChildren {
  CustomRequestsIdRoute: typeof CustomRequestsIdRoute
  CustomRequestsIndexRoute: typeof CustomRequestsIndexRoute
}

const CustomRequestsRouteChildren: CustomRequestsRouteChildren = {
  CustomRequestsIdRoute: CustomRequestsIdRoute,
  CustomRequestsIndexRoute: CustomRequestsIndexRoute,
}

const CustomRequestsRouteWithChildren = CustomRequestsRoute._addFileChildren(
  CustomRequestsRouteChildren,
)

interface OffersIdRouteChildren {
  OffersIdCheckoutRoute: typeof OffersIdCheckoutRoute
}

const OffersIdRouteChildren: OffersIdRouteChildren = {
  OffersIdCheckoutRoute: OffersIdCheckoutRoute,
}

const OffersIdRouteWithChildren = OffersIdRoute._addFileChildren(
  OffersIdRouteChildren,
)

interface OffersRouteChildren {
  OffersIdRoute: typeof OffersIdRouteWithChildren
  OffersIndexRoute: typeof OffersIndexRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersIdRoute: OffersIdRouteWithChildren,
  OffersIndexRoute: OffersIndexRoute,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface RfqRouteChildren {
  RfqIdRoute: typeof RfqIdRoute
  RfqNewRoute: typeof RfqNewRoute
  RfqIndexRoute: typeof RfqIndexRoute
}

const RfqRouteChildren: RfqRouteChildren = {
  RfqIdRoute: RfqIdRoute,
  RfqNewRoute: RfqNewRoute,
  RfqIndexRoute: RfqIndexRoute,
}

const RfqRouteWithChildren = RfqRoute._addFileChildren(RfqRouteChildren)

interface SupplierPortalRouteChildren {
  SupplierPortalInventoryRoute: typeof SupplierPortalInventoryRoute
  SupplierPortalMessagesRoute: typeof SupplierPortalMessagesRoute
  SupplierPortalOrdersRoute: typeof SupplierPortalOrdersRoute
  SupplierPortalPreviewRoute: typeof SupplierPortalPreviewRoute
  SupplierPortalQuoteRequestsRoute: typeof SupplierPortalQuoteRequestsRoute
  SupplierPortalVerificationRoute: typeof SupplierPortalVerificationRoute
  SupplierPortalIndexRoute: typeof SupplierPortalIndexRoute
  SupplierPortalProductsNewRoute: typeof SupplierPortalProductsNewRoute
  SupplierPortalProductsIndexRoute: typeof SupplierPortalProductsIndexRoute
}

const SupplierPortalRouteChildren: SupplierPortalRouteChildren = {
  SupplierPortalInventoryRoute: SupplierPortalInventoryRoute,
  SupplierPortalMessagesRoute: SupplierPortalMessagesRoute,
  SupplierPortalOrdersRoute: SupplierPortalOrdersRoute,
  SupplierPortalPreviewRoute: SupplierPortalPreviewRoute,
  SupplierPortalQuoteRequestsRoute: SupplierPortalQuoteRequestsRoute,
  SupplierPortalVerificationRoute: SupplierPortalVerificationRoute,
  SupplierPortalIndexRoute: SupplierPortalIndexRoute,
  SupplierPortalProductsNewRoute: SupplierPortalProductsNewRoute,
  SupplierPortalProductsIndexRoute: SupplierPortalProductsIndexRoute,
}

const SupplierPortalRouteWithChildren = SupplierPortalRoute._addFileChildren(
  SupplierPortalRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  CustomRequestsRoute: CustomRequestsRouteWithChildren,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OffersRoute: OffersRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  RfqRoute: RfqRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SupplierPortalRoute: SupplierPortalRouteWithChildren,
  SuppliersRoute: SuppliersRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardSupplierRoute: DashboardSupplierRoute,
  OnboardingBuyerRoute: OnboardingBuyerRoute,
  OnboardingSupplierRoute: OnboardingSupplierRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
