/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomRequestsRouteImport } from './routes/custom-requests'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RfqIndexRouteImport } from './routes/rfq.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as CustomRequestsIndexRouteImport } from './routes/custom-requests.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as RfqNewRouteImport } from './routes/rfq.new'
import { Route as RfqIdRouteImport } from './routes/rfq.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OnboardingSupplierRouteImport } from './routes/onboarding.supplier'
import { Route as OnboardingBuyerRouteImport } from './routes/onboarding.buyer'
import { Route as OffersIdRouteImport } from './routes/offers.$id'
import { Route as DashboardSupplierRouteImport } from './routes/dashboard.supplier'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as CustomRequestsIdRouteImport } from './routes/custom-requests.$id'
import { Route as AdminSafetyRouteImport } from './routes/admin.safety'
import { Route as OffersIdCheckoutRouteImport } from './routes/offers.$id.checkout'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRequestsRoute = CustomRequestsRouteImport.update({
  id: '/custom-requests',
  path: '/custom-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIndexRoute = RfqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RfqRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OffersRoute,
} as any)
const CustomRequestsIndexRoute = CustomRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomRequestsRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)
const RfqNewRoute = RfqNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RfqRoute,
} as any)
const RfqIdRoute = RfqIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RfqRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const OnboardingSupplierRoute = OnboardingSupplierRouteImport.update({
  id: '/onboarding/supplier',
  path: '/onboarding/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBuyerRoute = OnboardingBuyerRouteImport.update({
  id: '/onboarding/buyer',
  path: '/onboarding/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OffersRoute,
} as any)
const DashboardSupplierRoute = DashboardSupplierRouteImport.update({
  id: '/dashboard/supplier',
  path: '/dashboard/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRequestsIdRoute = CustomRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomRequestsRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const OffersIdCheckoutRoute = OffersIdCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => OffersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/custom-requests': typeof CustomRequestsRouteWithChildren
  '/docs': typeof DocsRoute
  '/messages': typeof MessagesRoute
  '/offers': typeof OffersRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/rfq': typeof RfqRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/admin/safety': typeof AdminSafetyRoute
  '/custom-requests/$id': typeof CustomRequestsIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
  '/offers/$id': typeof OffersIdRouteWithChildren
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/supplier': typeof OnboardingSupplierRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/custom-requests/': typeof CustomRequestsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/offers/$id/checkout': typeof OffersIdCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/docs': typeof DocsRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/admin/safety': typeof AdminSafetyRoute
  '/custom-requests/$id': typeof CustomRequestsIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
  '/offers/$id': typeof OffersIdRouteWithChildren
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/supplier': typeof OnboardingSupplierRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/custom-requests': typeof CustomRequestsIndexRoute
  '/offers': typeof OffersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/rfq': typeof RfqIndexRoute
  '/offers/$id/checkout': typeof OffersIdCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/custom-requests': typeof CustomRequestsRouteWithChildren
  '/docs': typeof DocsRoute
  '/messages': typeof MessagesRoute
  '/offers': typeof OffersRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/rfq': typeof RfqRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/admin/safety': typeof AdminSafetyRoute
  '/custom-requests/$id': typeof CustomRequestsIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
  '/offers/$id': typeof OffersIdRouteWithChildren
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/supplier': typeof OnboardingSupplierRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/custom-requests/': typeof CustomRequestsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/offers/$id/checkout': typeof OffersIdCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/custom-requests'
    | '/docs'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/products'
    | '/rfq'
    | '/suppliers'
    | '/admin/safety'
    | '/custom-requests/$id'
    | '/dashboard/buyer'
    | '/dashboard/supplier'
    | '/offers/$id'
    | '/onboarding/buyer'
    | '/onboarding/supplier'
    | '/orders/$id'
    | '/products/$id'
    | '/rfq/$id'
    | '/rfq/new'
    | '/suppliers/$id'
    | '/custom-requests/'
    | '/offers/'
    | '/products/'
    | '/rfq/'
    | '/offers/$id/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/docs'
    | '/messages'
    | '/orders'
    | '/suppliers'
    | '/admin/safety'
    | '/custom-requests/$id'
    | '/dashboard/buyer'
    | '/dashboard/supplier'
    | '/offers/$id'
    | '/onboarding/buyer'
    | '/onboarding/supplier'
    | '/orders/$id'
    | '/products/$id'
    | '/rfq/$id'
    | '/rfq/new'
    | '/suppliers/$id'
    | '/custom-requests'
    | '/offers'
    | '/products'
    | '/rfq'
    | '/offers/$id/checkout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/custom-requests'
    | '/docs'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/products'
    | '/rfq'
    | '/suppliers'
    | '/admin/safety'
    | '/custom-requests/$id'
    | '/dashboard/buyer'
    | '/dashboard/supplier'
    | '/offers/$id'
    | '/onboarding/buyer'
    | '/onboarding/supplier'
    | '/orders/$id'
    | '/products/$id'
    | '/rfq/$id'
    | '/rfq/new'
    | '/suppliers/$id'
    | '/custom-requests/'
    | '/offers/'
    | '/products/'
    | '/rfq/'
    | '/offers/$id/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomRequestsRoute: typeof CustomRequestsRouteWithChildren
  DocsRoute: typeof DocsRoute
  MessagesRoute: typeof MessagesRoute
  OffersRoute: typeof OffersRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  RfqRoute: typeof RfqRouteWithChildren
  SuppliersRoute: typeof SuppliersRouteWithChildren
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardSupplierRoute: typeof DashboardSupplierRoute
  OnboardingBuyerRoute: typeof OnboardingBuyerRoute
  OnboardingSupplierRoute: typeof OnboardingSupplierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-requests': {
      id: '/custom-requests'
      path: '/custom-requests'
      fullPath: '/custom-requests'
      preLoaderRoute: typeof CustomRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/': {
      id: '/rfq/'
      path: '/'
      fullPath: '/rfq/'
      preLoaderRoute: typeof RfqIndexRouteImport
      parentRoute: typeof RfqRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/offers/': {
      id: '/offers/'
      path: '/'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof OffersRoute
    }
    '/custom-requests/': {
      id: '/custom-requests/'
      path: '/'
      fullPath: '/custom-requests/'
      preLoaderRoute: typeof CustomRequestsIndexRouteImport
      parentRoute: typeof CustomRequestsRoute
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/rfq/new': {
      id: '/rfq/new'
      path: '/new'
      fullPath: '/rfq/new'
      preLoaderRoute: typeof RfqNewRouteImport
      parentRoute: typeof RfqRoute
    }
    '/rfq/$id': {
      id: '/rfq/$id'
      path: '/$id'
      fullPath: '/rfq/$id'
      preLoaderRoute: typeof RfqIdRouteImport
      parentRoute: typeof RfqRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/onboarding/supplier': {
      id: '/onboarding/supplier'
      path: '/onboarding/supplier'
      fullPath: '/onboarding/supplier'
      preLoaderRoute: typeof OnboardingSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/buyer': {
      id: '/onboarding/buyer'
      path: '/onboarding/buyer'
      fullPath: '/onboarding/buyer'
      preLoaderRoute: typeof OnboardingBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$id': {
      id: '/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof OffersRoute
    }
    '/dashboard/supplier': {
      id: '/dashboard/supplier'
      path: '/dashboard/supplier'
      fullPath: '/dashboard/supplier'
      preLoaderRoute: typeof DashboardSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-requests/$id': {
      id: '/custom-requests/$id'
      path: '/$id'
      fullPath: '/custom-requests/$id'
      preLoaderRoute: typeof CustomRequestsIdRouteImport
      parentRoute: typeof CustomRequestsRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/offers/$id/checkout': {
      id: '/offers/$id/checkout'
      path: '/checkout'
      fullPath: '/offers/$id/checkout'
      preLoaderRoute: typeof OffersIdCheckoutRouteImport
      parentRoute: typeof OffersIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSafetyRoute: typeof AdminSafetyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSafetyRoute: AdminSafetyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomRequestsRouteChildren {
  CustomRequestsIdRoute: typeof CustomRequestsIdRoute
  CustomRequestsIndexRoute: typeof CustomRequestsIndexRoute
}

const CustomRequestsRouteChildren: CustomRequestsRouteChildren = {
  CustomRequestsIdRoute: CustomRequestsIdRoute,
  CustomRequestsIndexRoute: CustomRequestsIndexRoute,
}

const CustomRequestsRouteWithChildren = CustomRequestsRoute._addFileChildren(
  CustomRequestsRouteChildren,
)

interface OffersIdRouteChildren {
  OffersIdCheckoutRoute: typeof OffersIdCheckoutRoute
}

const OffersIdRouteChildren: OffersIdRouteChildren = {
  OffersIdCheckoutRoute: OffersIdCheckoutRoute,
}

const OffersIdRouteWithChildren = OffersIdRoute._addFileChildren(
  OffersIdRouteChildren,
)

interface OffersRouteChildren {
  OffersIdRoute: typeof OffersIdRouteWithChildren
  OffersIndexRoute: typeof OffersIndexRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersIdRoute: OffersIdRouteWithChildren,
  OffersIndexRoute: OffersIndexRoute,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface RfqRouteChildren {
  RfqIdRoute: typeof RfqIdRoute
  RfqNewRoute: typeof RfqNewRoute
  RfqIndexRoute: typeof RfqIndexRoute
}

const RfqRouteChildren: RfqRouteChildren = {
  RfqIdRoute: RfqIdRoute,
  RfqNewRoute: RfqNewRoute,
  RfqIndexRoute: RfqIndexRoute,
}

const RfqRouteWithChildren = RfqRoute._addFileChildren(RfqRouteChildren)

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  CustomRequestsRoute: CustomRequestsRouteWithChildren,
  DocsRoute: DocsRoute,
  MessagesRoute: MessagesRoute,
  OffersRoute: OffersRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  RfqRoute: RfqRouteWithChildren,
  SuppliersRoute: SuppliersRouteWithChildren,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardSupplierRoute: DashboardSupplierRoute,
  OnboardingBuyerRoute: OnboardingBuyerRoute,
  OnboardingSupplierRoute: OnboardingSupplierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
